### ISSUE TITLE
Performance test fails in 1.7

### ISSUE THREAD

**Issue by MarcMush** [timholy/ProgressMeter.jl#219]
The performance test fails on julia-1.7.0-rc1 and ProgressMeter#master (doesn't happen with ProgressMeter 1.7.1)

tested on windows and wsl

```julia
(jl_EufnDT) pkg> test ProgressMeter
     Testing ProgressMeter
      Status `/tmp/jl_hQwVQU/Project.toml`
  [92933f4c] ProgressMeter v1.7.1 `https://github.com/timholy/ProgressMeter.jl.git#master`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [de0858da] Printf `@stdlib/Printf`
  [9a3f8284] Random `@stdlib/Random`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_hQwVQU/Manifest.toml`
  [92933f4c] ProgressMeter v1.7.1 `https://github.com/timholy/ProgressMeter.jl.git#master`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [de0858da] Printf `@stdlib/Printf`
  [9a3f8284] Random `@stdlib/Random`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [8dfed614] Test `@stdlib/Test`
  [4ec0a83e] Unicode `@stdlib/Unicode`
     Testing Running tests...
  0.092720 seconds (8 allocations: 480 bytes)
  0.012372 seconds
Progress: 100%|███████████████████████████████████████████████| Time: 0:00:00
Core: Test Failed at /home/mittel/.julia/packages/ProgressMeter/jLxQW/test/core.jl:51
  Expression: #= /home/mittel/.julia/packages/ProgressMeter/jLxQW/test/core.jl:51 =# @elapsed(prog_perf(10 ^ 7)) < 9 * #= /home/mittel/.julia/packages/ProgressMeter/jLxQW/test/core.jl:51 =# @elapsed(noprog_perf(10 ^ 7))
   Evaluated: 0.4294283 < 0.1127664
Stacktrace:
 [1] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] top-level scope
   @ ~/.julia/packages/ProgressMeter/jLxQW/test/core.jl:51
```

**Comment by garrison** [comment]
Hmm.  The constant factor in this comparison started as 40, which [I found not to be high enough to pass on a julia 1.6 prerelease](https://github.com/timholy/ProgressMeter.jl/pull/175#pullrequestreview-555787017).  Later, this constant was [lowered to 8](https://github.com/timholy/ProgressMeter.jl/commit/45e562e708f70c6e805b7ce94e35e3fe8c889d50#diff-90c3a7a047872b9929e6577e16ad589a77552d0de0400c98cf303b6b7204e683), and later it was [increased to 9](https://github.com/timholy/ProgressMeter.jl/commit/dfa86be7103266a33f4f02da81425fbf6c7e2a0e#diff-90c3a7a047872b9929e6577e16ad589a77552d0de0400c98cf303b6b7204e683).  It seems that all of these changes have made it into ProgressMeter.jl 1.7.1, though.  The [two](https://github.com/timholy/ProgressMeter.jl/commit/e1c7c7127848ee270b6770e03971d326afad2b85) [commits](https://github.com/timholy/ProgressMeter.jl/commit/5b74b84e2abf225b492a61e65ef575e59b6d7353) to `master` since then do not seem suspicious to me.
