### ISSUE TITLE
Incorrect print when progress bar is longer than console width

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#51]
Code:
```julia
using ProgressMeter

N = 100
p = Progress(N, 1, "Computing...", 50)
for i=1:N
  sleep(0.1)
  next!(p)
end
```
Result in small console:
![bug](https://cloud.githubusercontent.com/assets/3345261/17271219/c8fc05ac-563b-11e6-99f1-71c0f6baf613.png)

If I reduce the length of the bar to 30 for example, it works fine.

**Comment by tlycken** [comment]
I think this is by design; if you don't specify a width, we'll try to infer one from the size of the console.

**Comment by juliohm** [comment]
@tlycken what do you mean? By design the progress bar looks like a stairway?

**Comment by juliohm** [comment]
I am trying to understand why this is not an issue. Shouldn't this situation be handled differently? If the specified size is inconsistent, fallback to a consistent size? I don't know about the implementation details and what makes a size "inconsistent" with the console width. Having a stairway instead of a progress bar is not something I expect as a user.

**Comment by tlycken** [comment]
First, the technical reason to why it becomes a staircase with this input: As this library works for updating the bar, we simply go back to the beginning of the line and print a new bar, effectively overwriting the previous one. When the line has overflown to the next, we go back to the beginning of *that* line instead (since it's just by printing a carriage return character to the console), so the new status is written on the next line instead of on the same.

Now, I'm not sure what the best behavior is either.

We currently have two ways of showing progress with respect to the bar length argument - include it, or don't. If you don't, we infer it from the console with. If you do, there are (as I see it) two options on how to handle it:

1. Respect your input, and give you responsibility to choose something that works.

2. Evaluate if your input seems sane, and if it doesn't, override it with something that does (but maybe stays as close to your input as possible).

Currently we're doing number 1 - probably mostly because it's the easy one to implement, but I do think there is merit in not overriding user input. If you want a bar length of 1500, and you say so explicitly, why should we deny you?

If we want to switch to option two, we have to define a few things: what constitutes a "sane" bar length? If we get an "insane" one specified, how do we choose a sane one to replace it? This might be easy  - for example, I think we already have code to calculate what the bar length should be to fill the screen precisely, so anything longer than that is insane. And anything shorter than a few characters would also not make sense, I guess. Finally, choosing a sane one might be as simple as `sane = trunc(user_provided, sane_min, sane_max)` (but I'd want a warning emitted that we're not using the user-supplied value). A PR implementing this would be most welcome :)

**Comment by juliohm** [comment]
I agree with the current strategy Tim, it makes sense to honor user input.

It would be great to make users of this package aware of this side effect though. If someone decides to minimize the console other than the package developer, the stairway will appear in the client and the developer will never know. Thank you for the time explaining it, very helpful.
